import Foundation

public enum AgentPolicyLevel: String, Codable, CaseIterable, Identifiable, Sendable {
    case locked
    case review
    case build
    case network
    case autonomous
    case custom

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .locked: "Locked"
        case .review: "Review"
        case .build: "Build"
        case .network: "Network"
        case .autonomous: "Autonomous"
        case .custom: "Custom"
        }
    }

    public var shortDescription: String {
        switch self {
        case .locked:
            "Read and plan only."
        case .review:
            "Inspect work and ask before edits, broad shell, network, or credentials."
        case .build:
            "Edit scoped files and run approved build or test commands."
        case .network:
            "Use approved connectors and network destinations."
        case .autonomous:
            "Broad provider permissions for trusted or isolated work."
        case .custom:
            "Advanced user-defined ASTRA and provider rules."
        }
    }

    public var symbolName: String {
        switch self {
        case .locked: "lock.fill"
        case .review: "lock.shield.fill"
        case .build: "hammer.fill"
        case .network: "network"
        case .autonomous: "exclamationmark.shield.fill"
        case .custom: "slider.horizontal.3"
        }
    }

    public var isBroadPermissionMode: Bool {
        self == .autonomous
    }

    public static func normalized(_ rawValue: String?) -> AgentPolicyLevel {
        guard let rawValue,
              let level = AgentPolicyLevel(rawValue: rawValue.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
        else {
            return .review
        }
        return level
    }
}

public enum AgentPolicyScope: String, Codable, Sendable, CaseIterable {
    case builtInDefault = "built_in_default"
    case globalDefault = "global_default"
    case workspaceDefault = "workspace_default"
    case taskOverride = "task_override"
    case oneRunEscalation = "one_run_escalation"

    public var displayName: String {
        switch self {
        case .builtInDefault: "Built-in default"
        case .globalDefault: "Global default"
        case .workspaceDefault: "Workspace default"
        case .taskOverride: "Task override"
        case .oneRunEscalation: "One-run escalation"
        }
    }
}

public enum PolicyConfigOwnership: String, Codable, Sendable, CaseIterable {
    case generated
    case userOverride = "user_override"
    case externalManaged = "external_managed"
    case mixed

    public var displayName: String {
        switch self {
        case .generated: "Generated by ASTRA"
        case .userOverride: "User override"
        case .externalManaged: "Managed externally"
        case .mixed: "Mixed"
        }
    }
}

public enum PolicyDiagnosticSeverity: String, Codable, Sendable, Comparable, CaseIterable {
    case info
    case warning
    case blocked

    public static func < (lhs: PolicyDiagnosticSeverity, rhs: PolicyDiagnosticSeverity) -> Bool {
        let order: [PolicyDiagnosticSeverity] = [.info, .warning, .blocked]
        return order.firstIndex(of: lhs)! < order.firstIndex(of: rhs)!
    }
}

public struct PolicyDiagnostic: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var severity: PolicyDiagnosticSeverity
    public var title: String
    public var message: String
    public var affectedCapability: String?
    public var remediation: String?

    public init(
        id: String,
        severity: PolicyDiagnosticSeverity,
        title: String,
        message: String,
        affectedCapability: String? = nil,
        remediation: String? = nil
    ) {
        self.id = id
        self.severity = severity
        self.title = title
        self.message = message
        self.affectedCapability = affectedCapability
        self.remediation = remediation
    }
}

public enum PolicyEnforcementTier: String, Codable, Sendable, CaseIterable {
    case providerNative = "provider_native"
    case astraBrokered = "astra_brokered"
    case osSandboxed = "os_sandboxed"
    case mixed

    public var displayName: String {
        switch self {
        case .providerNative: "Provider Native"
        case .astraBrokered: "ASTRA Brokered"
        case .osSandboxed: "OS Sandboxed"
        case .mixed: "Mixed"
        }
    }
}

public struct AgentPolicy: Codable, Equatable, Sendable {
    public var level: AgentPolicyLevel
    public var allowedTools: [String]
    public var askFirstTools: [String]
    public var deniedTools: [String]
    public var allowedShellPatterns: [String]
    public var askFirstShellPatterns: [String]
    public var deniedShellPatterns: [String]
    public var allowedURLPatterns: [String]
    public var deniedURLPatterns: [String]
    public var credentialLabels: [String]

    public init(
        level: AgentPolicyLevel,
        allowedTools: [String],
        askFirstTools: [String] = [],
        deniedTools: [String] = [],
        allowedShellPatterns: [String] = [],
        askFirstShellPatterns: [String] = [],
        deniedShellPatterns: [String] = [],
        allowedURLPatterns: [String] = [],
        deniedURLPatterns: [String] = [],
        credentialLabels: [String] = []
    ) {
        self.level = level
        self.allowedTools = Self.unique(allowedTools)
        self.askFirstTools = Self.unique(askFirstTools)
        self.deniedTools = Self.unique(deniedTools)
        self.allowedShellPatterns = Self.unique(allowedShellPatterns)
        self.askFirstShellPatterns = Self.unique(askFirstShellPatterns)
        self.deniedShellPatterns = Self.unique(deniedShellPatterns)
        self.allowedURLPatterns = Self.unique(allowedURLPatterns)
        self.deniedURLPatterns = Self.unique(deniedURLPatterns)
        self.credentialLabels = Self.unique(credentialLabels)
    }

    public static func preset(_ level: AgentPolicyLevel) -> AgentPolicy {
        switch level {
        case .locked:
            AgentPolicy(
                level: .locked,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: [],
                deniedTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                deniedShellPatterns: ["*"],
                deniedURLPatterns: ["*"]
            )
        case .review:
            AgentPolicy(
                level: .review,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                deniedShellPatterns: [
                    "rm:*",
                    "sudo:*",
                    "chmod:*",
                    "chown:*",
                    "git push:*",
                    "deploy:*",
                    "publish:*"
                ]
            )
        case .build:
            AgentPolicy(
                level: .build,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash"],
                askFirstTools: ["WebFetch", "WebSearch"],
                allowedShellPatterns: ["git:*", "swift:*", "./script/*", "xcodebuild:*"],
                deniedShellPatterns: ["sudo:*", "rm:*", "git push:*", "deploy:*", "publish:*"]
            )
        case .network:
            AgentPolicy(
                level: .network,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                askFirstTools: ["Bash(curl:*)"],
                allowedShellPatterns: ["git:*", "swift:*", "./script/*", "xcodebuild:*", "curl:*"],
                deniedShellPatterns: ["sudo:*", "rm:*", "git push:*", "deploy:*", "publish:*"]
            )
        case .autonomous:
            AgentPolicy(
                level: .autonomous,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch", "Agent"],
                allowedShellPatterns: ["*"],
                allowedURLPatterns: ["*"]
            )
        case .custom:
            AgentPolicy(
                level: .custom,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"]
            )
        }
    }

    public static func legacy(skipPermissions: Bool) -> AgentPolicy {
        preset(skipPermissions ? .autonomous : .review)
    }

    public func providerAllowedTools(requestedTools: [String]) -> [String] {
        switch level {
        case .locked, .review:
            return Self.unique(allowedTools)
        case .build, .network:
            return Self.unique(requestedTools + allowedTools).filter { !deniedTools.contains($0) }
        case .autonomous, .custom:
            let tools = requestedTools.isEmpty ? allowedTools : requestedTools + allowedTools
            return Self.unique(tools).filter { !deniedTools.contains($0) }
        }
    }

    public func applyingOneRunAllowedTools(_ approvedTools: [String]) -> AgentPolicy {
        let approved = Self.unique(approvedTools)
        guard !approved.isEmpty else { return self }

        var policy = self
        policy.allowedTools = Self.unique(policy.allowedTools + approved)
        policy.askFirstTools = policy.askFirstTools.filter { !approved.contains($0) }
        policy.deniedTools = policy.deniedTools.filter { !approved.contains($0) }
        return policy
    }

    private static func unique(_ values: [String]) -> [String] {
        Array(Set(values.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty })).sorted()
    }
}

public struct ProviderPolicyFeatures: Codable, Equatable, Sendable {
    public var supportsAllowTools: Bool
    public var supportsDenyTools: Bool
    public var supportsAskFirstMode: Bool
    public var supportsPathScoping: Bool
    public var supportsURLAllowlist: Bool
    public var supportsURLDenylist: Bool
    public var supportsSecretEnvRedaction: Bool
    public var supportsGeneratedSettingsFile: Bool
    public var supportsPerRunFlags: Bool
    public var supportsInteractiveCallbacks: Bool
    public var supportsManagedSettings: Bool
    public var supportsMachineReadableEvents: Bool
    public var supportsBroadAllowAll: Bool

    public init(
        supportsAllowTools: Bool,
        supportsDenyTools: Bool,
        supportsAskFirstMode: Bool,
        supportsPathScoping: Bool,
        supportsURLAllowlist: Bool,
        supportsURLDenylist: Bool,
        supportsSecretEnvRedaction: Bool,
        supportsGeneratedSettingsFile: Bool,
        supportsPerRunFlags: Bool,
        supportsInteractiveCallbacks: Bool,
        supportsManagedSettings: Bool,
        supportsMachineReadableEvents: Bool,
        supportsBroadAllowAll: Bool
    ) {
        self.supportsAllowTools = supportsAllowTools
        self.supportsDenyTools = supportsDenyTools
        self.supportsAskFirstMode = supportsAskFirstMode
        self.supportsPathScoping = supportsPathScoping
        self.supportsURLAllowlist = supportsURLAllowlist
        self.supportsURLDenylist = supportsURLDenylist
        self.supportsSecretEnvRedaction = supportsSecretEnvRedaction
        self.supportsGeneratedSettingsFile = supportsGeneratedSettingsFile
        self.supportsPerRunFlags = supportsPerRunFlags
        self.supportsInteractiveCallbacks = supportsInteractiveCallbacks
        self.supportsManagedSettings = supportsManagedSettings
        self.supportsMachineReadableEvents = supportsMachineReadableEvents
        self.supportsBroadAllowAll = supportsBroadAllowAll
    }
}

public struct PolicyRenderContext: Codable, Equatable, Sendable {
    public var runtimeID: AgentRuntimeID
    public var model: String
    public var workspacePath: String
    public var additionalPaths: [String]
    public var requestedAllowedTools: [String]
    public var localToolCommands: [String]
    public var environmentKeyNames: [String]
    public var credentialLabels: [String]
    public var providerFeatures: ProviderPolicyFeatures
    public var providerConfigOwnership: PolicyConfigOwnership
    public var existingProviderConfigSummary: String?

    public init(
        runtimeID: AgentRuntimeID,
        model: String,
        workspacePath: String,
        additionalPaths: [String],
        requestedAllowedTools: [String],
        localToolCommands: [String],
        environmentKeyNames: [String],
        credentialLabels: [String],
        providerFeatures: ProviderPolicyFeatures,
        providerConfigOwnership: PolicyConfigOwnership = .generated,
        existingProviderConfigSummary: String? = nil
    ) {
        self.runtimeID = runtimeID
        self.model = model
        self.workspacePath = workspacePath
        self.additionalPaths = Array(Set(additionalPaths)).sorted()
        self.requestedAllowedTools = Array(Set(requestedAllowedTools)).sorted()
        self.localToolCommands = Array(Set(localToolCommands)).sorted()
        self.environmentKeyNames = Array(Set(environmentKeyNames)).sorted()
        self.credentialLabels = Array(Set(credentialLabels)).sorted()
        self.providerFeatures = providerFeatures
        self.providerConfigOwnership = providerConfigOwnership
        self.existingProviderConfigSummary = existingProviderConfigSummary
    }
}

public struct ProviderPolicyRender: Codable, Equatable, Sendable {
    public var providerID: AgentRuntimeID
    public var adapterVersion: Int
    public var policyLevel: AgentPolicyLevel
    public var configOwnership: PolicyConfigOwnership
    public var permissionMode: String
    public var allowedTools: [String]
    public var askFirstTools: [String]
    public var deniedTools: [String]
    public var allowedShellPatterns: [String]
    public var askFirstShellPatterns: [String]
    public var deniedShellPatterns: [String]
    public var allowedURLPatterns: [String]
    public var deniedURLPatterns: [String]
    public var cliArgumentsSummary: [String]
    public var settingsSummary: String
    public var generatedConfigPreview: String
    public var enforcementTiers: [PolicyEnforcementTier]
    public var diagnostics: [PolicyDiagnostic]
    public var usesBroadProviderPermissions: Bool

    private enum CodingKeys: String, CodingKey {
        case providerID
        case adapterVersion
        case policyLevel
        case configOwnership
        case permissionMode
        case allowedTools
        case askFirstTools
        case deniedTools
        case allowedShellPatterns
        case askFirstShellPatterns
        case deniedShellPatterns
        case allowedURLPatterns
        case deniedURLPatterns
        case cliArgumentsSummary
        case settingsSummary
        case generatedConfigPreview
        case enforcementTiers
        case diagnostics
        case usesBroadProviderPermissions
    }

    public init(
        providerID: AgentRuntimeID,
        adapterVersion: Int,
        policyLevel: AgentPolicyLevel,
        configOwnership: PolicyConfigOwnership,
        permissionMode: String,
        allowedTools: [String],
        askFirstTools: [String] = [],
        deniedTools: [String],
        allowedShellPatterns: [String],
        askFirstShellPatterns: [String] = [],
        deniedShellPatterns: [String],
        allowedURLPatterns: [String],
        deniedURLPatterns: [String],
        cliArgumentsSummary: [String],
        settingsSummary: String,
        generatedConfigPreview: String,
        enforcementTiers: [PolicyEnforcementTier],
        diagnostics: [PolicyDiagnostic],
        usesBroadProviderPermissions: Bool
    ) {
        self.providerID = providerID
        self.adapterVersion = adapterVersion
        self.policyLevel = policyLevel
        self.configOwnership = configOwnership
        self.permissionMode = permissionMode
        self.allowedTools = allowedTools
        self.askFirstTools = askFirstTools
        self.deniedTools = deniedTools
        self.allowedShellPatterns = allowedShellPatterns
        self.askFirstShellPatterns = askFirstShellPatterns
        self.deniedShellPatterns = deniedShellPatterns
        self.allowedURLPatterns = allowedURLPatterns
        self.deniedURLPatterns = deniedURLPatterns
        self.cliArgumentsSummary = cliArgumentsSummary
        self.settingsSummary = settingsSummary
        self.generatedConfigPreview = generatedConfigPreview
        self.enforcementTiers = enforcementTiers
        self.diagnostics = diagnostics
        self.usesBroadProviderPermissions = usesBroadProviderPermissions
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        providerID = try container.decode(AgentRuntimeID.self, forKey: .providerID)
        adapterVersion = try container.decode(Int.self, forKey: .adapterVersion)
        policyLevel = try container.decode(AgentPolicyLevel.self, forKey: .policyLevel)
        configOwnership = try container.decode(PolicyConfigOwnership.self, forKey: .configOwnership)
        permissionMode = try container.decode(String.self, forKey: .permissionMode)
        allowedTools = try container.decode([String].self, forKey: .allowedTools)
        askFirstTools = try container.decodeIfPresent([String].self, forKey: .askFirstTools) ?? []
        deniedTools = try container.decode([String].self, forKey: .deniedTools)
        allowedShellPatterns = try container.decode([String].self, forKey: .allowedShellPatterns)
        askFirstShellPatterns = try container.decodeIfPresent([String].self, forKey: .askFirstShellPatterns) ?? []
        deniedShellPatterns = try container.decode([String].self, forKey: .deniedShellPatterns)
        allowedURLPatterns = try container.decode([String].self, forKey: .allowedURLPatterns)
        deniedURLPatterns = try container.decode([String].self, forKey: .deniedURLPatterns)
        cliArgumentsSummary = try container.decode([String].self, forKey: .cliArgumentsSummary)
        settingsSummary = try container.decode(String.self, forKey: .settingsSummary)
        generatedConfigPreview = try container.decodeIfPresent(String.self, forKey: .generatedConfigPreview) ?? ""
        enforcementTiers = try container.decode([PolicyEnforcementTier].self, forKey: .enforcementTiers)
        diagnostics = try container.decode([PolicyDiagnostic].self, forKey: .diagnostics)
        usesBroadProviderPermissions = try container.decode(Bool.self, forKey: .usesBroadProviderPermissions)
    }
}

public enum PolicyObservedEventKind: String, Codable, Sendable, CaseIterable {
    case toolUse = "tool_use"
    case toolResult = "tool_result"
    case deniedAction = "denied_action"
    case fileChange = "file_change"
    case networkAccess = "network_access"
}

public struct PolicyObservedEvent: Codable, Equatable, Sendable, Identifiable {
    public var id: UUID
    public var kind: PolicyObservedEventKind
    public var toolName: String?
    public var command: String?
    public var path: String?
    public var url: String?
    public var summary: String?

    public init(
        id: UUID = UUID(),
        kind: PolicyObservedEventKind,
        toolName: String? = nil,
        command: String? = nil,
        path: String? = nil,
        url: String? = nil,
        summary: String? = nil
    ) {
        self.id = id
        self.kind = kind
        self.toolName = toolName
        self.command = command
        self.path = path
        self.url = url
        self.summary = summary
    }

    public init?(providerEvent: ParsedEvent) {
        switch providerEvent {
        case .toolUse(let name, _, let input):
            let command = Self.firstString(in: input, keys: ["command", "cmd", "summary"])
            let path = Self.firstString(in: input, keys: ["file_path", "path", "target_path"])
            let url = Self.firstString(in: input, keys: ["url", "uri"])
                ?? command.flatMap(Self.firstURL(in:))
            let kind: PolicyObservedEventKind = if path != nil && Self.isMutationTool(name) {
                .fileChange
            } else if url != nil || Self.isNetworkTool(name) {
                .networkAccess
            } else {
                .toolUse
            }
            self.init(
                kind: kind,
                toolName: name,
                command: command,
                path: path,
                url: url,
                summary: command ?? path ?? url
            )
        case .toolResult(let toolId, let content):
            self.init(kind: .toolResult, toolName: toolId.isEmpty ? nil : toolId, summary: String(content.prefix(500)))
        case .permissionDenied(let tool, let reason):
            self.init(kind: .deniedAction, toolName: tool, summary: String(reason.prefix(500)))
        default:
            return nil
        }
    }

    private static func firstString(in input: [String: Any]?, keys: [String]) -> String? {
        guard let input else { return nil }
        for key in keys {
            if let value = input[key] as? String {
                let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty { return trimmed }
            }
        }
        return nil
    }

    private static func isMutationTool(_ tool: String) -> Bool {
        ["write", "edit", "multiedit"].contains(tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
    }

    private static func isNetworkTool(_ tool: String) -> Bool {
        ["webfetch", "websearch"].contains(tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
    }

    private static func firstURL(in text: String) -> String? {
        guard let regex = try? NSRegularExpression(pattern: #"https?://[^\s"')<>]+"#) else { return nil }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        guard let match = regex.firstMatch(in: text, range: range),
              let valueRange = Range(match.range, in: text) else {
            return nil
        }
        return String(text[valueRange])
    }
}

public struct RunPermissionManifest: Codable, Equatable, Sendable, Identifiable {
    public var id: UUID
    public var createdAt: Date
    public var taskID: UUID
    public var runID: UUID
    public var phase: String
    public var providerID: AgentRuntimeID
    public var providerVersion: String?
    public var model: String
    public var policyLevel: AgentPolicyLevel
    public var policyScope: AgentPolicyScope
    public var providerRender: ProviderPolicyRender
    public var workspacePath: String
    public var additionalPaths: [String]
    public var environmentKeyNames: [String]
    public var credentialLabels: [String]
    public var approvalsGranted: [String]
    public var observedToolUseCount: Int
    public var observedDeniedCount: Int
    public var observedFileChangeCount: Int

    public init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        taskID: UUID,
        runID: UUID,
        phase: String,
        providerID: AgentRuntimeID,
        providerVersion: String?,
        model: String,
        policyLevel: AgentPolicyLevel,
        policyScope: AgentPolicyScope,
        providerRender: ProviderPolicyRender,
        workspacePath: String,
        additionalPaths: [String],
        environmentKeyNames: [String],
        credentialLabels: [String],
        approvalsGranted: [String],
        observedToolUseCount: Int = 0,
        observedDeniedCount: Int = 0,
        observedFileChangeCount: Int = 0
    ) {
        self.id = id
        self.createdAt = createdAt
        self.taskID = taskID
        self.runID = runID
        self.phase = phase
        self.providerID = providerID
        self.providerVersion = providerVersion
        self.model = model
        self.policyLevel = policyLevel
        self.policyScope = policyScope
        self.providerRender = providerRender
        self.workspacePath = workspacePath
        self.additionalPaths = Array(Set(additionalPaths)).sorted()
        self.environmentKeyNames = Array(Set(environmentKeyNames)).sorted()
        self.credentialLabels = Array(Set(credentialLabels)).sorted()
        self.approvalsGranted = Array(Set(approvalsGranted)).sorted()
        self.observedToolUseCount = observedToolUseCount
        self.observedDeniedCount = observedDeniedCount
        self.observedFileChangeCount = observedFileChangeCount
    }
}
